---

- name: Install required packages
  yum: name={{ item }} state=present
  with_items: 
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - wget

- name: Get docker install script for CentOS
  get_url:
    url: https://get.docker.com/
    dest: /home/centos/docker_install
  when: ansible_distribution == 'CentOS'

- name: Install docker CentOS
  command: sh /home/centos/docker_install
  when: ansible_distribution == 'CentOS'

- name: Install docker AmazonLinux
  yum:
    name: docker
    state: present
  when: ansible_distribution == 'Amazon'

- name: Start docker service
  service:
    name: docker 
    state: started

- name: Start hello-world container
  command: docker run hello-world

